export const S = {

'AI 官网':[
  {t:'ChatGPT',u:'chat.openai.com',d:'OpenAI 对话 AI'},{t:'Claude',u:'claude.ai',d:'Anthropic 智能助手'},{t:'Gemini',u:'gemini.google.com',d:'Google AI 模型'},{t:'Perplexity',u:'perplexity.ai',d:'AI 搜索引擎'},{t:'Midjourney',u:'midjourney.com',d:'AI 图像生成'},{t:'Stable Diffusion',u:'stability.ai',d:'开源 AI 图像'},{t:'Suno AI',u:'suno.com',d:'AI 音乐创作'},{t:'Kimi',u:'kimi.moonshot.cn',d:'长文本 AI'},{t:'通义千问',u:'tongyi.aliyun.com',d:'阿里云 AI'},{t:'文心一言',u:'yiyan.baidu.com',d:'百度大模型'},{t:'豆包',u:'www.doubao.com',d:'字节跳动 AI'},{t:'DeepSeek',u:'chat.deepseek.com',d:'深度求索 AI'},{t:'智谱清言',u:'chatglm.cn',d:'智谱 AI'},{t:'讯飞星火',u:'xinghuo.xfyun.cn',d:'科大讯飞 AI'},{t:'天工 AI',u:'www.tiangong.cn',d:'昆仑万维'},{t:'Poe',u:'poe.com',d:'多模型聚合'},{t:'Copilot',u:'copilot.microsoft.com',d:'微软 AI'},{t:'Grok',u:'grok.com',d:'xAI 模型'},{t:'Runway',u:'runwayml.com',d:'AI 视频生成'},{t:'ElevenLabs',u:'elevenlabs.io',d:'AI 语音合成'},{t:'Character.AI',u:'character.ai',d:'AI 角色对话'},{t:'Jasper',u:'jasper.ai',d:'AI 营销写作'},{t:'Notion AI',u:'notion.so/product/ai',d:'AI 知识助手'},{t:'Udio',u:'udio.com',d:'AI 音乐生成'},{t:'扣子',u:'www.coze.cn',d:'字节 AI 开发'},{t:'海螺 AI',u:'hailuoai.com',d:'MiniMax 助手'},{t:'秘塔搜索',u:'metaso.cn',d:'AI 搜索'},{t:'Luma AI',u:'lumalabs.ai',d:'AI 3D/视频'},{t:'Ideogram',u:'ideogram.ai',d:'AI 图文生成'},{t:'通义万相',u:'wanx.aliyun.com',d:'阿里 AI 绘画'},
],
'开发工具':[
  {t:'GitHub',u:'github.com',d:'代码托管协作'},{t:'GitLab',u:'gitlab.com',d:'DevOps 平台'},{t:'Gitee',u:'gitee.com',d:'国内代码托管'},{t:'Bitbucket',u:'bitbucket.org',d:'Atlassian 托管'},{t:'VS Code',u:'code.visualstudio.com',d:'微软编辑器'},{t:'Cursor',u:'cursor.sh',d:'AI 编辑器'},{t:'Windsurf',u:'windsurf.com',d:'AI IDE'},{t:'Zed',u:'zed.dev',d:'高性能编辑器'},{t:'JetBrains',u:'jetbrains.com',d:'专业 IDE'},{t:'Docker Hub',u:'hub.docker.com',d:'容器镜像'},{t:'Vercel',u:'vercel.com',d:'前端部署'},{t:'Netlify',u:'netlify.com',d:'静态站部署'},{t:'Railway',u:'railway.app',d:'全栈云部署'},{t:'Render',u:'render.com',d:'云应用托管'},{t:'Supabase',u:'supabase.com',d:'开源 BaaS'},{t:'Firebase',u:'firebase.google.com',d:'Google BaaS'},{t:'Figma',u:'figma.com',d:'协作设计'},{t:'Notion',u:'notion.so',d:'全能工作空间'},{t:'Linear',u:'linear.app',d:'项目管理'},{t:'Jira',u:'atlassian.com/software/jira',d:'项目管理'},{t:'Postman',u:'postman.com',d:'API 调试'},{t:'Insomnia',u:'insomnia.rest',d:'API 客户端'},{t:'Bruno',u:'usebruno.com',d:'开源 API 调试'},{t:'Cloudflare',u:'dash.cloudflare.com',d:'CDN 安全'},{t:'Sentry',u:'sentry.io',d:'错误监控'},{t:'Grafana',u:'grafana.com',d:'监控可视化'},{t:'Terraform',u:'terraform.io',d:'IaC 工具'},{t:'Warp',u:'warp.dev',d:'AI 终端'},{t:'CodePen',u:'codepen.io',d:'前端实验场'},{t:'StackBlitz',u:'stackblitz.com',d:'浏览器 IDE'},{t:'Replit',u:'replit.com',d:'在线 IDE'},{t:'CodeSandbox',u:'codesandbox.io',d:'在线沙盒'},{t:'npm',u:'npmjs.com',d:'Node 包管理'},{t:'PyPI',u:'pypi.org',d:'Python 包'},{t:'MDN',u:'developer.mozilla.org',d:'Web 文档'},{t:'Can I Use',u:'caniuse.com',d:'浏览器兼容'},{t:'Regex101',u:'regex101.com',d:'正则测试'},{t:'Excalidraw',u:'excalidraw.com',d:'手绘白板'},{t:'TypeScript',u:'typescriptlang.org',d:'TS 文档'},{t:'Tailwind',u:'tailwindcss.com',d:'原子 CSS'},{t:'Vite',u:'vite.dev',d:'构建工具'},{t:'DevDocs',u:'devdocs.io',d:'聚合文档'},{t:'Bundlephobia',u:'bundlephobia.com',d:'包体积分析'},{t:'JSON Editor',u:'jsoneditoronline.org',d:'JSON 编辑'},{t:'JSFiddle',u:'jsfiddle.net',d:'JS 在线测试'},{t:'Glitch',u:'glitch.com',d:'在线应用搭建'},{t:'Codeium',u:'codeium.com',d:'AI 代码补全'},{t:'Sourcegraph',u:'sourcegraph.com',d:'代码搜索'},{t:'Trae',u:'trae.ai',d:'字节跳动 AI IDE'},{t:'Claude Code',u:'claude.ai',d:'Anthropic 终端编程'},{t:'Codex',u:'chatgpt.com',d:'OpenAI 编程智能体'},{t:'Lovable',u:'lovable.dev',d:'自然语言建站'},{t:'Bolt',u:'bolt.new',d:'AI 全栈搭建'},{t:'v0',u:'v0.dev',d:'Vercel AI UI'},{t:'AiPy',u:'aipy.com',d:'零代码 AI 编程'},{t:'Qoder',u:'qoder.ai',d:'阿里智能编码'},{t:'CodeBuddy',u:'codebuddy.qq.com',d:'腾讯 AI 编码'},{t:'灵珠',u:'lzhu.cn',d:'DeepSeek 应用创作'},{t:'码上飞',u:'mashangfei.com',d:'AI 生成应用'},{t:'美团 NoCode',u:'nocode.meituan.com',d:'零代码平台'},{t:'Devin',u:'devin.ai',d:'AI 软件工程师'},{t:'GitHub Copilot',u:'github.com/features/copilot',d:'AI 结对编程'},
],
'API 服务':[
  {t:'OpenAI API',u:'platform.openai.com',d:'GPT / DALL-E'},{t:'Anthropic',u:'console.anthropic.com',d:'Claude API'},{t:'Google AI',u:'aistudio.google.com',d:'Gemini API'},{t:'Hugging Face',u:'huggingface.co',d:'开源模型'},{t:'Replicate',u:'replicate.com',d:'云端推理'},{t:'Together AI',u:'together.ai',d:'开源推理'},{t:'硅基流动',u:'siliconflow.cn',d:'国产 API'},{t:'Cohere',u:'cohere.com',d:'企业 AI'},{t:'Groq',u:'groq.com',d:'高速推理'},{t:'Mistral',u:'mistral.ai',d:'欧洲 AI'},{t:'AWS Bedrock',u:'aws.amazon.com/bedrock',d:'亚马逊 AI'},{t:'Azure AI',u:'ai.azure.com',d:'微软 AI'},{t:'OpenRouter',u:'openrouter.ai',d:'多模型路由'},{t:'Fireworks',u:'fireworks.ai',d:'快速推理'},{t:'Deepinfra',u:'deepinfra.com',d:'低成本推理'},{t:'百炼',u:'bailian.console.aliyun.com',d:'阿里模型服务'},{t:'Pinecone',u:'pinecone.io',d:'向量数据库'},{t:'Weaviate',u:'weaviate.io',d:'向量搜索'},{t:'LangChain',u:'langchain.com',d:'LLM 框架'},{t:'Stripe',u:'stripe.com/docs/api',d:'支付 API'},{t:'Twilio',u:'twilio.com',d:'通信 API'},{t:'Algolia',u:'algolia.com',d:'搜索 API'},
],
'常用网站':[
  {t:'百度',u:'baidu.com',d:'搜索引擎'},{t:'哔哩哔哩',u:'bilibili.com',d:'视频弹幕'},{t:'知乎',u:'zhihu.com',d:'知识问答'},{t:'微博',u:'weibo.com',d:'社交媒体'},{t:'淘宝',u:'taobao.com',d:'综合购物'},{t:'京东',u:'jd.com',d:'自营电商'},{t:'拼多多',u:'pinduoduo.com',d:'社交电商'},{t:'抖音',u:'douyin.com',d:'短视频'},{t:'小红书',u:'xiaohongshu.com',d:'生活分享'},{t:'今日头条',u:'toutiao.com',d:'信息流'},{t:'豆瓣',u:'douban.com',d:'影评书评'},{t:'微信读书',u:'weread.qq.com',d:'在线阅读'},{t:'飞书',u:'feishu.cn',d:'企业协作'},{t:'钉钉',u:'dingtalk.com',d:'企业办公'},{t:'语雀',u:'yuque.com',d:'知识管理'},{t:'WPS',u:'kdocs.cn',d:'在线办公'},{t:'腾讯文档',u:'docs.qq.com',d:'协作文档'},{t:'石墨文档',u:'shimo.im',d:'云端文档'},{t:'携程',u:'ctrip.com',d:'旅行预订'},{t:'美团',u:'meituan.com',d:'生活服务'},{t:'大众点评',u:'dianping.com',d:'餐饮点评'},{t:'12306',u:'12306.cn',d:'铁路购票'},{t:'高德地图',u:'amap.com',d:'地图导航'},{t:'天眼查',u:'tianyancha.com',d:'企业查询'},{t:'网易',u:'163.com',d:'综合门户'},{t:'腾讯网',u:'qq.com',d:'综合门户'},{t:'闲鱼',u:'2.taobao.com',d:'二手交易'},{t:'唯品会',u:'vip.com',d:'品牌特卖'},{t:'苏宁',u:'suning.com',d:'家电数码'},{t:'58同城',u:'58.com',d:'分类信息'},{t:'链家',u:'lianjia.com',d:'房产中介'},{t:'汽车之家',u:'autohome.com.cn',d:'汽车资讯'},
],
'国际网站':[
  {t:'Google',u:'google.com',d:'全球搜索'},{t:'Wikipedia',u:'wikipedia.org',d:'自由百科'},{t:'Reddit',u:'reddit.com',d:'社区论坛'},{t:'X / Twitter',u:'x.com',d:'社交媒体'},{t:'Facebook',u:'facebook.com',d:'社交网络'},{t:'Instagram',u:'instagram.com',d:'图片社交'},{t:'LinkedIn',u:'linkedin.com',d:'职业社交'},{t:'Amazon',u:'amazon.com',d:'全球电商'},{t:'eBay',u:'ebay.com',d:'拍卖电商'},{t:'WhatsApp',u:'web.whatsapp.com',d:'即时通讯'},{t:'Telegram',u:'web.telegram.org',d:'加密通讯'},{t:'Discord',u:'discord.com',d:'社群通讯'},{t:'Slack',u:'slack.com',d:'团队协作'},{t:'Medium',u:'medium.com',d:'博客平台'},{t:'Substack',u:'substack.com',d:'邮件订阅'},{t:'Quora',u:'quora.com',d:'问答社区'},{t:'TikTok',u:'tiktok.com',d:'短视频'},{t:'Zoom',u:'zoom.us',d:'视频会议'},{t:'Notion',u:'notion.so',d:'工作空间'},{t:'Walmart',u:'walmart.com',d:'零售电商'},{t:'Pinterest',u:'pinterest.com',d:'图片灵感'},{t:'Airbnb',u:'airbnb.com',d:'民宿短租'},{t:'Uber',u:'uber.com',d:'出行服务'},{t:'Booking',u:'booking.com',d:'酒店预订'},{t:'PayPal',u:'paypal.com',d:'在线支付'},{t:'Etsy',u:'etsy.com',d:'手工电商'},
],
'技术社区':[
  {t:'CSDN',u:'csdn.net',d:'开发者社区'},{t:'掘金',u:'juejin.cn',d:'技术平台'},{t:'SegmentFault',u:'segmentfault.com',d:'技术问答'},{t:'V2EX',u:'v2ex.com',d:'创意社区'},{t:'Stack Overflow',u:'stackoverflow.com',d:'编程问答'},{t:'Dev.to',u:'dev.to',d:'开发者社区'},{t:'Hacker News',u:'news.ycombinator.com',d:'科技新闻'},{t:'Product Hunt',u:'producthunt.com',d:'新产品发现'},{t:'InfoQ',u:'infoq.cn',d:'技术资讯'},{t:'OSChina',u:'oschina.net',d:'开源中国'},{t:'LeetCode',u:'leetcode.cn',d:'算法刷题'},{t:'牛客',u:'nowcoder.com',d:'求职刷题'},{t:'Hashnode',u:'hashnode.com',d:'开发者博客'},{t:'36氪',u:'36kr.com',d:'科技资讯'},{t:'少数派',u:'sspai.com',d:'数字生活'},{t:'Lobsters',u:'lobste.rs',d:'技术链接'},{t:'Ruby China',u:'ruby-china.org',d:'Ruby 社区'},{t:'IndieHackers',u:'indiehackers.com',d:'独立开发者'},
],
'影音娱乐':[
  {t:'YouTube',u:'youtube.com',d:'全球视频'},{t:'Netflix',u:'netflix.com',d:'影视流媒体'},{t:'Spotify',u:'spotify.com',d:'音乐流媒体'},{t:'Disney+',u:'disneyplus.com',d:'迪士尼影视'},{t:'哔哩哔哩',u:'bilibili.com',d:'视频弹幕'},{t:'爱奇艺',u:'iqiyi.com',d:'视频平台'},{t:'优酷',u:'youku.com',d:'视频平台'},{t:'腾讯视频',u:'v.qq.com',d:'视频平台'},{t:'芒果TV',u:'mgtv.com',d:'湖南卫视'},{t:'网易云音乐',u:'music.163.com',d:'音乐平台'},{t:'QQ音乐',u:'y.qq.com',d:'音乐平台'},{t:'Twitch',u:'twitch.tv',d:'游戏直播'},{t:'斗鱼',u:'douyu.com',d:'游戏直播'},{t:'虎牙',u:'huya.com',d:'游戏直播'},{t:'Steam',u:'store.steampowered.com',d:'游戏商店'},{t:'Epic Games',u:'epicgames.com',d:'游戏商店'},{t:'IMDb',u:'imdb.com',d:'影视数据库'},{t:'Apple Music',u:'music.apple.com',d:'苹果音乐'},{t:'Max',u:'max.com',d:'HBO 流媒体'},{t:'Prime Video',u:'primevideo.com',d:'亚马逊视频'},{t:'咪咕视频',u:'miguvideo.com',d:'咪咕影视'},{t:'酷狗音乐',u:'kugou.com',d:'音乐平台'},{t:'SoundCloud',u:'soundcloud.com',d:'音乐分享'},
],
'设计资源':[
  {t:'Dribbble',u:'dribbble.com',d:'设计展示'},{t:'Behance',u:'behance.net',d:'创意作品'},{t:'Pinterest',u:'pinterest.com',d:'图片灵感'},{t:'Unsplash',u:'unsplash.com',d:'免费图片'},{t:'Pexels',u:'pexels.com',d:'免费素材'},{t:'IconFont',u:'iconfont.cn',d:'阿里图标'},{t:'Lucide',u:'lucide.dev',d:'开源图标'},{t:'Heroicons',u:'heroicons.com',d:'Tailwind 图标'},{t:'Coolors',u:'coolors.co',d:'配色生成'},{t:'Mobbin',u:'mobbin.com',d:'设计参考'},{t:'Awwwards',u:'awwwards.com',d:'设计奖'},{t:'Canva',u:'canva.com',d:'在线设计'},{t:'Remove.bg',u:'remove.bg',d:'AI 去背景'},{t:'LottieFiles',u:'lottiefiles.com',d:'动画资源'},{t:'Framer',u:'framer.com',d:'交互原型'},{t:'Whimsical',u:'whimsical.com',d:'流程图'},{t:'Adobe Color',u:'color.adobe.com',d:'Adobe 配色'},{t:'Material Design',u:'m3.material.io',d:'Google 设计'},{t:'Ant Design',u:'ant.design',d:'蚂蚁设计系统'},{t:'Figma Community',u:'figma.com/community',d:'Figma 模板'},
],
'教育学习':[
  {t:'Coursera',u:'coursera.org',d:'名校在线课程'},{t:'Udemy',u:'udemy.com',d:'技能课程'},{t:'edX',u:'edx.org',d:'大学公开课'},{t:'Khan Academy',u:'khanacademy.org',d:'免费教育'},{t:'Codecademy',u:'codecademy.com',d:'编程学习'},{t:'freeCodeCamp',u:'freecodecamp.org',d:'免费学编程'},{t:'W3Schools',u:'w3schools.com',d:'Web 教程'},{t:'Kaggle',u:'kaggle.com',d:'数据科学'},{t:'Brilliant',u:'brilliant.org',d:'数理思维'},{t:'Duolingo',u:'duolingo.com',d:'语言学习'},{t:'中国大学MOOC',u:'icourse163.org',d:'国家精品课'},{t:'学堂在线',u:'xuetangx.com',d:'清华慕课'},{t:'慕课网',u:'imooc.com',d:'IT 技能学习'},{t:'网易公开课',u:'open.163.com',d:'公开课'},{t:'极客时间',u:'time.geekbang.org',d:'技术专栏'},{t:'Skillshare',u:'skillshare.com',d:'创意课程'},{t:'Pluralsight',u:'pluralsight.com',d:'技术培训'},{t:'LinkedIn Learning',u:'linkedin.com/learning',d:'职业课程'},{t:'腾讯课堂',u:'ke.qq.com',d:'在线课堂'},{t:'知乎知学堂',u:'zhihu.com/education',d:'知乎教育'},
],
'新闻资讯':[
  {t:'新华网',u:'xinhuanet.com',d:'国家通讯社'},{t:'人民网',u:'people.com.cn',d:'人民日报'},{t:'央视网',u:'cctv.com',d:'央视新闻'},{t:'澎湃新闻',u:'thepaper.cn',d:'时政深度'},{t:'界面新闻',u:'jiemian.com',d:'商业财经'},{t:'观察者网',u:'guancha.cn',d:'时政评论'},{t:'凤凰网',u:'ifeng.com',d:'综合资讯'},{t:'南方周末',u:'infzm.com',d:'深度报道'},{t:'BBC',u:'bbc.com',d:'英国广播'},{t:'CNN',u:'cnn.com',d:'美国有线'},{t:'Reuters',u:'reuters.com',d:'路透社'},{t:'The Verge',u:'theverge.com',d:'科技资讯'},{t:'TechCrunch',u:'techcrunch.com',d:'科技创业'},{t:'Wired',u:'wired.com',d:'科技文化'},{t:'Ars Technica',u:'arstechnica.com',d:'技术深度'},{t:'The Guardian',u:'theguardian.com',d:'卫报新闻'},{t:'AP News',u:'apnews.com',d:'美联社'},{t:'NHK',u:'www3.nhk.or.jp',d:'日本放送'},
],
'金融理财':[
  {t:'东方财富',u:'eastmoney.com',d:'财经门户'},{t:'同花顺',u:'10jqka.com.cn',d:'股票软件'},{t:'雪球',u:'xueqiu.com',d:'投资社区'},{t:'富途牛牛',u:'futunn.com',d:'港美股'},{t:'老虎证券',u:'tigerbrokers.com',d:'美港股'},{t:'天天基金',u:'fund.eastmoney.com',d:'基金平台'},{t:'蚂蚁财富',u:'antfortune.com',d:'综合理财'},{t:'Bloomberg',u:'bloomberg.com',d:'彭博财经'},{t:'Yahoo Finance',u:'finance.yahoo.com',d:'雅虎财经'},{t:'MarketWatch',u:'marketwatch.com',d:'市场观察'},{t:'Investing',u:'investing.com',d:'投资数据'},{t:'CoinMarketCap',u:'coinmarketcap.com',d:'加密行情'},{t:'CoinGecko',u:'coingecko.com',d:'加密数据'},{t:'Binance',u:'binance.com',d:'加密交易所'},{t:'招商银行',u:'cmbchina.com',d:'招行网银'},{t:'支付宝',u:'alipay.com',d:'支付服务'},
],
'云服务':[
  {t:'AWS',u:'aws.amazon.com',d:'亚马逊云'},{t:'Google Cloud',u:'cloud.google.com',d:'谷歌云'},{t:'Azure',u:'azure.microsoft.com',d:'微软云'},{t:'阿里云',u:'aliyun.com',d:'阿里云计算'},{t:'腾讯云',u:'cloud.tencent.com',d:'腾讯云计算'},{t:'华为云',u:'huaweicloud.com',d:'华为云计算'},{t:'百度智能云',u:'cloud.baidu.com',d:'百度云'},{t:'火山引擎',u:'volcengine.com',d:'字节跳动云'},{t:'DigitalOcean',u:'digitalocean.com',d:'开发者云'},{t:'Vultr',u:'vultr.com',d:'云服务器'},{t:'Linode',u:'linode.com',d:'Akamai 云'},{t:'Hetzner',u:'hetzner.com',d:'欧洲云服务器'},{t:'Fly.io',u:'fly.io',d:'边缘部署'},{t:'PlanetScale',u:'planetscale.com',d:'Serverless DB'},{t:'Neon',u:'neon.tech',d:'Serverless PG'},{t:'Upstash',u:'upstash.com',d:'Serverless Redis'},{t:'Zeabur',u:'zeabur.com',d:'一键部署'},{t:'京东云',u:'jdcloud.com',d:'京东云计算'},
],
'自定义':[],
};
